version: 2

jobs:
  build:
    branches:
      only:
        - dev
        - master
        - ci
    docker:
      - image: "circleci/rust:1.33"
    steps:
      - checkout
      - run:
          name: Building
          command: cargo build
      - run:
          name: Testing
          command: cargo test
